# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'checkmate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya', '~> 13.0.1'
pod 'SwiftyJSON'

  # Pods for checkmate

end
